# Screen widths are required. May use widthxheight format or just width.
screen_widths:
  - 320
  - 768
  - 1024
  - 1280

# Domains are required, but may be passed in as arguments. Key is used in filename and as label.
#domains:
#  domain1: http://domain.dev
#  domain2: https://domain.prod

# Paths are required, but often merged from a site-specific file. Key is used in filename and label.
#paths:
#  home: /
#  about: /about
#  sitemap: /sitemap

# (required) The directory that your screenshots will be stored in
directory: shots

# resize to each screen width, or reload at each screen width. (The former is more efficient).
resize_or_reload: 'resize'

# the engine to run Wraith with. Ignored in Visualify -- currently always uses Chrome.
browser: "chrome"

#phantomjs_options: --ignore-ssl-errors=yes
# These items are currently ignored by visualify.
threads: 3
settle: 4

# Ignored.
before_capture: 'javascript/wait--chrome.js'

# Ignored.
fuzz: 20%

# (required) The maximum acceptable level of difference (in %) between two images before
# Visualify reports a failure.
threshold: 6

# Gallery options (required for visualify gallery):
gallery:
  template: 'slideshow_template' # currently loaded from configs/ directory.
  thumb_width:  200
  thumb_height: 400

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
# Not yet implemented in visualify -- always diffs_first.
mode: diffs_first
